name: Keep-Alive Bot Render

on:
  schedule:
    # Ejecuta cada 5 minutos para garantizar que Render nunca alcance los 15 min de inactividad
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Web Service
        run: |
          curl -s -S -f -m 30 https://asistente-discord-sj3k.onrender.com || true

